version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: car-rental-db
    restart: always
    environment:
      MYSQL_DATABASE: car_rental_db
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"  # Maps port 3306 on your PC to the container
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: